"use client";

import { useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { aiResourceFinder, type AiResourceFinderOutput } from "@/ai/flows/resource-finder";
import { Lightbulb, Search, ExternalLink, Loader2 } from "lucide-react";

export function ResourceFinderCard() {
  const [searchQuery, setSearchQuery] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [resources, setResources] = useState<AiResourceFinderOutput["resources"]>([]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) {
      setError("Please enter a search query.");
      return;
    }

    setIsLoading(true);
    setError(null);
    setResources([]);

    try {
      const result = await aiResourceFinder({ searchQuery });
      setResources(result.resources);
    } catch (err) {
      console.error("Error finding resources:", err);
      setError("Failed to find resources. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Card className="shadow-md">
      <CardHeader>
        <div className="flex items-center gap-2 mb-1">
          <Lightbulb className="h-6 w-6 text-primary" />
          <CardTitle className="text-xl">AI Resource Finder</CardTitle>
        </div>
        <CardDescription>Get personalized links to learning resources and documentation.</CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="flex gap-2">
            <Input
              type="text"
              placeholder="e.g., 'React state management tutorials'"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              disabled={isLoading}
              className="flex-grow"
            />
            <Button type="submit" disabled={isLoading}>
              {isLoading ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Search className="mr-2 h-4 w-4" />
              )}
              Find
            </Button>
          </div>
        </form>

        {error && (
          <Alert variant="destructive" className="mt-4">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {resources.length > 0 && (
          <div className="mt-6 space-y-3">
            <h4 className="font-semibold text-md">Suggested Resources:</h4>
            <ul className="space-y-2">
              {resources.map((resource, index) => (
                <li key={index} className="border p-3 rounded-md hover:bg-accent/50 transition-colors">
                  <a
                    href={resource.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between group"
                  >
                    <span className="text-sm font-medium text-primary group-hover:underline">{resource.title}</span>
                    <ExternalLink className="h-4 w-4 text-muted-foreground group-hover:text-primary" />
                  </a>
                </li>
              ))}
            </ul>
          </div>
        )}
         {isLoading && ( // Show skeleton loaders while loading results
          <div className="mt-6 space-y-3">
            <h4 className="font-semibold text-md">Searching for resources...</h4>
            <div className="space-y-2 animate-pulse">
              {[1,2,3].map(i => (
                <div key={i} className="border p-3 rounded-md">
                  <div className="h-4 bg-muted rounded w-3/4"></div>
                </div>
              ))}
            </div>
          </div>
        )}
      </CardContent>
      {resources.length > 0 && (
         <CardFooter>
            <p className="text-xs text-muted-foreground">Resources generated by AI. Always verify information.</p>
         </CardFooter>
      )}
    </Card>
  );
}
